[SERVO]
#servo_min = 1050
#servo_max = 1250
servo_min = 990
servo_max = 1350
min_angle = 270
max_angle = 0

[HEAD_SERVO]
head_pin = 17
servo_min = 990
servo_max = 1350
min_angle = 20
max_angle = 300
move_time = 1

[CONTROLLER]
style = 1
threshold = 2000
level1 = 1500
level2 = 2500
level3 = 3500
filtered_level1 = 1000
filtered_level2 = 2500
filtered_level3 = 4000

[PROP]
#prop_trigger = TIMER
prop_trigger = PIR
delay = 1
#delay = 500
eyes = OFF
trigger_out = OFF

[PINS]
jaw_pin = 18
pir_pin = 23
eyes_pin = 25
trigger_out_pin = 16
